const spacerLarge=String.fromCharCode(8193)+String.fromCharCode(8193)+String.fromCharCode(8193);class SkillType{constructor(b,a,c){this.name=b;this.label=a;this.categoryGroup=c}}class SkillCategory{constructor(b,a,c){this.name=b;this.label=a;this.skillGroup=c}}class Skill{constructor(b,a,c,e,d){this.name=b;this.label=a;this.description=c;this.tierGroup=e;this.moreInfo=d;this.levelMax=e.length}}
class SkillTier{constructor(b,a,c,e,d,f){this.level=b;this.effect=a;this.cost=c;this.minLevelPlayer=e;this.minLevelCategory=d;this.moreInfo=f}}
const skillsCommon=new SkillType("common","Common Skills",[new SkillCategory("common","Common",[new Skill("slide","Slide Attack","Increased chance of taking enemy down when sliding ("+String.fromCharCode(8615)+" + "+String.fromCharCode(9632)+").",[new SkillTier(1,"Power: 30"+spacerLarge+"Knockdown +30%",1,-1,-1,["Slight increase to max movement distance."]),new SkillTier(2,"Power: 34"+spacerLarge+"Knockdown +40%",1,10,-1,["Slight increase to max movement distance."]),new SkillTier(3,"Power: 40"+spacerLarge+
"Knockdown +55%",2,20,3,["Moderate increase to max movement distance."]),new SkillTier(4,"Power: 46"+spacerLarge+"Knockdown +70%",3,31,3,["Great increase to max movement distance."]),new SkillTier(5,"Power: 60"+spacerLarge+"Knockdown +100%",4,40,6,["Massive increase to max movement distance."])],["The max distance of the slide attack increases as the level of the skill increases.","The max time of execution does not change with changes to the skill level, thus you will cover further max distances in the same amount of time you would cover the default max distance."]),
new Skill("wealthHealth","Wealth to Health","Picking up coins recovers HP.",[new SkillTier(1,"HP recovered per coin: 2",1,-1,-1,[""]),new SkillTier(2,"HP recovered per coin: 3",1,5,-1,[""]),new SkillTier(3,"HP recovered per coin: 5",2,14,3,[""]),new SkillTier(4,"HP recovered per coin: 7",3,27,3,[""]),new SkillTier(5,"HP recovered per coin: 10",4,42,6,[""])],[""]),new Skill("moneyPower","Money is Power","Picking up coins adds to your score.",[new SkillTier(1,"Score obtained +10",1,-1,-1,[""]),new SkillTier(2,
"Score obtained +20",1,8,-1,[""]),new SkillTier(3,"Score obtained +40",2,17,3,[""]),new SkillTier(4,"Score obtained +60",3,29,3,[""]),new SkillTier(5,"Score obtained +100",4,43,6,[""])],[""]),new Skill("vitalityBoost","Vitality Boost","Increases your max HP.",[new SkillTier(1,"Max HP +20",1,-1,-1,[""]),new SkillTier(2,"Max HP +35",1,7,-1,[""]),new SkillTier(3,"Max HP +50",1,13,3,[""]),new SkillTier(4,"Max HP +65",2,19,3,[""]),new SkillTier(5,"Max HP +80",2,25,6,[""]),new SkillTier(6,"Max HP +100",
3,31,6,[""]),new SkillTier(7,"Max HP 120",3,38,9,[""]),new SkillTier(8,"Max HP +145",4,45,9,[""]),new SkillTier(9,"Max HP +170",4,52,12,[""]),new SkillTier(10,"Max HP +200",6,59,12,[""])],[""]),new Skill("nutritionist","Nutritionist","Increases the healing effectiveness of food.",[new SkillTier(1,"Recovery Amount +20%",1,-1,-1,[""]),new SkillTier(2,"Recovery Amount +25%",1,11,-1,[""]),new SkillTier(3,"Recovery Amount +30%",2,24,3,[""]),new SkillTier(4,"Recovery Amount +35%",3,37,3,[""]),new SkillTier(5,
"Recovery Amount +50%",4,51,6,[""])],[""]),new Skill("maintenance","Maintenance","Grants a chance that using a temporary weapon won't decrease the number of uses.",[new SkillTier(1,"Chance that # of uses won't deplete: 20%",1,6,0,[""]),new SkillTier(2,"Chance that # of uses won't deplete: 25%",1,13,0,[""]),new SkillTier(3,"Chance that # of uses won't deplete: 30%",2,23,3,[""]),new SkillTier(4,"Chance that # of uses won't deplete: 35%",3,34,3,[""]),new SkillTier(5,"Chance that # of uses won't deplete: 50%",
4,47,6,[""])],[""]),new Skill("adroitHands","Adroit Hands","Reduces cooldown time in between using items.",[new SkillTier(1,"Item use cooldown -10%",1,9,0,[""]),new SkillTier(2,"Item use cooldown -15%",1,16,0,[""]),new SkillTier(3,"Item use cooldown -20%",2,22,3,[""]),new SkillTier(4,"Item use cooldown -25%",2,29,3,[""]),new SkillTier(5,"Item use cooldown -30%",3,36,6,[""]),new SkillTier(6,"Item use cooldown -35%",3,44,6,[""]),new SkillTier(7,"Item use cooldown -50%",5,53,9,[""])],[""]),new Skill("evasion",
"Evasion","Increases the number of times you can evade ( R1 ) in a row.",[new SkillTier(1,"Number of evasions +1",2,12,0,[""]),new SkillTier(2,"Number of evasions +2",3,32,3,[""]),new SkillTier(3,"Number of evasions +3",4,52,6,[""])],[""]),new Skill("deepPockets","Deep Pockets","Increases the number of item slots in Bags.",[new SkillTier(1,"Number of Bag slots: 8",2,15,0,[""]),new SkillTier(2,"Number of Bag slots: 9",4,30,3,[""]),new SkillTier(3,"Number of Bag slots: 10",6,50,6,[""])],[""])])]),skillsFighter=
new SkillType("fighter","Fighter Skills",[new SkillCategory("attack","Attack",[new Skill("cycloneMasher","Cyclone Masher","Increases duration of aerial attacks. Rapidly press \u25a0 to activate.",[new SkillTier(1,"Power: 20"+spacerLarge+"Descent speed -30%",1,-1,-1,[""]),new SkillTier(2,"Power: 22"+spacerLarge+"Descent speed -45"+spacerLarge+"Attack range: 105%",1,10,-1,[""]),new SkillTier(3,"Power: 23"+spacerLarge+"Descent speed -60"+spacerLarge+"Attack range: 110%",2,19,3,[""]),new SkillTier(4,
"Power: 25"+spacerLarge+"Descent speed -75"+spacerLarge+"Attack range: 115%",3,30,3,[""]),new SkillTier(5,"Power: 30"+spacerLarge+"Descent speed -95"+spacerLarge+"Attack range: 125%",5,45,6,[""])],[""]),new Skill("shockwave","Shockwave","Send out ripples that creep along the ground. Activate with \u21a5 + \u25a0.",[new SkillTier(1,"Power: 15"+spacerLarge+"Number of shockwaves: 2",1,-1,-1,[""]),new SkillTier(2,"Power: 18"+spacerLarge+"Number of shockwaves: 2",1,8,-1,[""]),new SkillTier(3,"Power: 23"+
spacerLarge+"Number of shockwaves: 3",2,16,3,[""]),new SkillTier(4,"Power: 30"+spacerLarge+"Number of shockwaves: 3",3,26,3,[""]),new SkillTier(5,"Power: 45"+spacerLarge+"Number of shockwaves: 4",5,40,6,["Vertical reach of shockwaves greatly increased."])],[""]),new Skill("judgement","Judgement","Add a shockwave to your diving attack. Press \u21a7 + \u25a0 in midair to activate.",[new SkillTier(1,"Power: 40",1,3,-1,[""]),new SkillTier(2,"Power: 44"+spacerLarge+"Shockwave range: 120%",1,12,-1,[""]),
new SkillTier(3,"Power: 46"+spacerLarge+"Shockwave range: 140%",2,21,3,[""]),new SkillTier(4,"Power: 48"+spacerLarge+"Shockwave range: 160%",2,30,3,[""]),new SkillTier(5,"Power: 50"+spacerLarge+"Shockwave range: 180%",3,39,6,[""]),new SkillTier(6,"Power: 52"+spacerLarge+"Shockwave range: 200%",3,48,6,[""]),new SkillTier(7,"Power: 60"+spacerLarge+"Shockwave range: 300%",5,57,9,["Number of shockwaves: 5"])],[""]),new Skill("rebuke","Rebuke","Power Smash and its shockwaves are strengthened. Press \u25cf on the ground.",
[new SkillTier(1,"Power: 440"+spacerLarge+"Shockwave Power: 165",1,6,-1,[""]),new SkillTier(2,"Power: 480"+spacerLarge+"Shockwave Power: 180"+spacerLarge+"Shockwave range: 115%",1,14,-1,[""]),new SkillTier(3,"Power: 520"+spacerLarge+"Shockwave Power: 195"+spacerLarge+"Shockwave range: 130%",2,22,3,[""]),new SkillTier(4,"Power: 560"+spacerLarge+"Shockwave Power: 210"+spacerLarge+"Shockwave range: 145%",2,31,3,[""]),new SkillTier(5,"Power: 600"+spacerLarge+"Shockwave Power: 225"+spacerLarge+"Shockwave range: 160%",
3,40,6,[""]),new SkillTier(6,"Power: 640"+spacerLarge+"Shockwave Power: 240"+spacerLarge+"Shockwave range: 185%",3,49,6,[""]),new SkillTier(7,"Power: 800"+spacerLarge+"Shockwave Power: 300"+spacerLarge+"Shockwave range: 285%",5,58,9,[""])],[""]),new Skill("tempest","Tempest Edge","Create a powerful storm of sword attacks by rapidly pressing \u25a0.",[new SkillTier(1,"Power: 30"+spacerLarge+"Duration: 1.5s",3,15,-1,[""]),new SkillTier(2,"Power: 33"+spacerLarge+"Duration: 1.9s"+spacerLarge+"Attack range: 103%",
1,20,-1,[""]),new SkillTier(3,"Power: 36"+spacerLarge+"Duration: 2.2"+spacerLarge+"Attack range: 106%",1,25,3,[""]),new SkillTier(4,"Power: 41"+spacerLarge+"Duration: 2.4s"+spacerLarge+"Attack range: 110%",2,30,3,[""]),new SkillTier(5,"Power: 45"+spacerLarge+"Duration: 2.7s"+spacerLarge+"Attack range: 114%",2,35,6,[""]),new SkillTier(6,"Power: 50"+spacerLarge+"Duration: 2.9s"+spacerLarge+"Attack range: 119%",3,40,6,[""]),new SkillTier(7,"Power: 54"+spacerLarge+"Duration: 3.2s"+spacerLarge+"Attack range: 124%",
3,45,9,[""]),new SkillTier(8,"Power: 60"+spacerLarge+"Duration: 3.4s"+spacerLarge+"Attack range: 130%",4,50,9,[""]),new SkillTier(9,"Power: 66"+spacerLarge+"Duration: 3.7s"+spacerLarge+"Attack range: 136%",4,55,12,[""]),new SkillTier(10,"Power: 75"+spacerLarge+"Duration: 4.2s"+spacerLarge+"Attack range: 150%",6,60,12,[""])],[""])]),new SkillCategory("defense","Defense",[new Skill("coverAll","Cover Allies","Hold \u25a0 on the ground to use your shield to protect allies and temporarily increase your attack power upon successful block.",
[new SkillTier(1,"Max ATK Damage Increase: +40%",1,-1,-1,[""]),new SkillTier(2,"Effect range: 125%"+spacerLarge+"Max ATK Damage Increase: +70%",2,17,-1,[""]),new SkillTier(3,"Effect range: 200%"+spacerLarge+"Max ATK Damage Increase: +100%",3,36,3,[""])],[""]),new Skill("reflexGuard","Reflex Guard","Grants chance to automatically guard when attacked.",[new SkillTier(1,"Chance of auto-defense: 25%",1,-1,-1,[""]),new SkillTier(2,"Chance of auto-defense: 30%",1,7,-1,[""]),new SkillTier(3,"Chance of auto-defense: 35%",
2,16,3,[""]),new SkillTier(4,"Chance of auto-defense: 40%",2,27,3,[""]),new SkillTier(5,"Chance of auto-defense: 50%",3,35,6,[""])],[""]),new Skill("bash","Bash","Press \u25a0 after blocking an attack to counterattack and stun with your shield.",[new SkillTier(1,"Power: 20"+spacerLarge+"Stun rate: 20%"+spacerLarge+"Bash Dealt damage +10%",1,4,-1,[""]),new SkillTier(2,"Power: 24"+spacerLarge+"Stun rate: 25%"+spacerLarge+"Bash Dealt damage +20%",1,9,-1,[""]),new SkillTier(3,"Power: 28"+spacerLarge+
"Stun rate: 30%"+spacerLarge+"Bash Dealt damage +40%",1,14,3,[""]),new SkillTier(4,"Power: 32"+spacerLarge+"Stun rate: 35%"+spacerLarge+"Bash Dealt damage +60%",2,19,3,[""]),new SkillTier(5,"Power: 36"+spacerLarge+"Stun rate: 40%"+spacerLarge+"Bash Dealt damage +80%",2,24,6,[""]),new SkillTier(6,"Power: 40"+spacerLarge+"Stun rate: 45%"+spacerLarge+"Bash Dealt damage +100%",2,29,6,[""]),new SkillTier(7,"Power: 44"+spacerLarge+"Stun rate: 50%"+spacerLarge+"Bash Dealt damage +120%",3,34,9,[""]),new SkillTier(8,
"Power: 48"+spacerLarge+"Stun rate: 55%"+spacerLarge+"Bash Dealt damage +140%",3,40,9,[""]),new SkillTier(9,"Power: 52"+spacerLarge+"Stun rate: 60%"+spacerLarge+"Bash Dealt damage +160%",4,47,12,[""]),new SkillTier(10,"Power: 60"+spacerLarge+"Stun rate: 80%"+spacerLarge+"Bash Dealt damage +200%",6,54,12,[""])],[""]),new Skill("reflect","Missile Reflect","Grants a chance to reflect projectile weapons when guarding with your shield.",[new SkillTier(1,"Chance of reflection: 30%",1,11,-1,[""]),new SkillTier(2,
"Chance of reflection: 35%"+spacerLarge+"Reflected shot Dealt damage +20%",1,16,-1,[""]),new SkillTier(3,"Chance of reflection: 40%"+spacerLarge+"Reflected shot Dealt damage +40%",1,21,3,[""]),new SkillTier(4,"Chance of reflection: 45%"+spacerLarge+"Reflected shot Dealt damage +65%",2,27,3,[""]),new SkillTier(5,"Chance of reflection: 50%"+spacerLarge+"Reflected shot Dealt damage +90%",2,32,6,[""]),new SkillTier(6,"Chance of reflection: 55%"+spacerLarge+"Reflected shot Dealt damage +115%",2,37,6,[""]),
new SkillTier(7,"Chance of reflection: 65%"+spacerLarge+"Reflected shot Dealt damage +140%",3,43,9,[""]),new SkillTier(8,"Chance of reflection: 75%"+spacerLarge+"Reflected shot Dealt damage +165%",3,48,9,[""]),new SkillTier(9,"Chance of reflection: 90%"+spacerLarge+"Reflected shot Dealt damage +200%",4,53,12,[""]),new SkillTier(10,"Chance of reflection: 100%"+spacerLarge+"Reflected shot Dealt damage +250%",6,58,12,[""])],[""])]),new SkillCategory("supplemental","Supplemental",[new Skill("distraction",
"Distraction","Call enemies' attention to yourself. Use the Skill item Distraction.",[new SkillTier(1,"Uses: 5"+spacerLarge+"Enemies distracted: 5"+spacerLarge+"Dealt damage +10%",1,-1,-1,[""]),new SkillTier(2,"Uses: 5"+spacerLarge+"Enemies distracted: 6"+spacerLarge+"Dealt damage +20%",2,12,-1,[""]),new SkillTier(3,"Uses: 5"+spacerLarge+"Enemies distracted: 9"+spacerLarge+"Dealt damage +30%",3,24,3,[""])]),new Skill("sacrifice","Sacrifice","Take damage inflicted on your allies. Use the Skill item Sacrifice.",
[new SkillTier(1,"Uses: 3"+spacerLarge+"Damage taken -30%",1,5,-1,[""]),new SkillTier(2,"Uses: 3"+spacerLarge+"Damage taken -40%",1,11,-1,[""]),new SkillTier(3,"Uses: 3"+spacerLarge+"Damage taken -50%",2,19,3,[""]),new SkillTier(4,"Uses: 3"+spacerLarge+"Damage taken -60%",3,29,3,[""]),new SkillTier(5,"Uses: 3"+spacerLarge+"Damage taken -70%",4,42,6,[""])]),new Skill("shieldTactics","Shield Tactics","Boost your shield's effectiveness and make it harder to be moved.",[new SkillTier(1,"Guard resistance +20%"+
spacerLarge+"Shield durability loss -5%",1,9,-1,[""]),new SkillTier(2,"Guard resistance +30%"+spacerLarge+"Shield durability loss -7%",1,13,-1,[""]),new SkillTier(3,"Guard resistance +40%"+spacerLarge+"Shield durability loss -10%",2,18,3,[""]),new SkillTier(4,"Guard resistance +50%"+spacerLarge+"Shield durability loss -13%",2,23,3,[""]),new SkillTier(5,"Guard resistance +60%"+spacerLarge+"Shield durability loss -16%",3,28,6,[""]),new SkillTier(6,"Guard resistance +70%"+spacerLarge+"Shield durability loss -19%",
3,33,6,[""]),new SkillTier(7,"Guard resistance +85%"+spacerLarge+"Shield durability loss -25%",4,38,9,[""]),new SkillTier(8,"Guard resistance +100%"+spacerLarge+"Shield durability loss -31%",4,44,9,[""]),new SkillTier(9,"Guard resistance +120%"+spacerLarge+"Shield durability loss -40%",5,50,12,[""]),new SkillTier(10,"Guard resistance +150%"+spacerLarge+"Shield durability loss -50%",6,56,12,[""])])])]),skillsAmazon=new SkillType("amazon","Amazon Skills",[new SkillCategory("air","Air",[new Skill("stunWave",
"Stun Wave","A diving attack that creates a shockwave. \u21a7 + \u25a0 in midair to use.",[new SkillTier(1,"Power: 20",1,-1,-1,[""]),new SkillTier(2,"Power: 24"+spacerLarge+"Shockwave distance 110%",1,6,-1,[""]),new SkillTier(3,"Power: 28"+spacerLarge+"Shockwave distance 120%",2,12,3,[""]),new SkillTier(4,"Power: 32"+spacerLarge+"Shockwave distance 130%",2,18,3,[""]),new SkillTier(5,"Power: 36"+spacerLarge+"Shockwave distance 140%",3,25,6,[""]),new SkillTier(6,"Power: 40"+spacerLarge+"Shockwave distance 150%",
3,33,6,[""]),new SkillTier(7,"Power: 60"+spacerLarge+"Shockwave distance 190%",5,42,9,[""])]),new Skill("neckSplitter","Neck Splitter","Double jump + \u21a7 + \u25a0 for a diving attack that's effective against downed enemies.",[new SkillTier(1,"Power: 150"+spacerLarge+"Dealt damage +100%",1,3,-1,[""]),new SkillTier(2,"Power: 155"+spacerLarge+"Dealt damage +105%",1,8,-1,[""]),new SkillTier(3,"Power: 162"+spacerLarge+"Dealt damage +110%",1,14,3,[""]),new SkillTier(4,"Power: 169"+spacerLarge+"Dealt damage +115%",
2,20,3,[""]),new SkillTier(5,"Power: 176"+spacerLarge+"Dealt damage +120%",2,26,6,[""]),new SkillTier(6,"Power: 182"+spacerLarge+"Dealt damage +130%",3,32,6,[""]),new SkillTier(7,"Power: 189"+spacerLarge+"Dealt damage +140%",3,38,9,[""]),new SkillTier(8,"Power: 196"+spacerLarge+"Dealt damage +155%",4,44,9,[""]),new SkillTier(9,"Power: 203"+spacerLarge+"Dealt damage +170%",4,50,12,[""]),new SkillTier(10,"Power: 230"+spacerLarge+"Dealt damage +200%",6,56,12,[""])]),new Skill("revolution","Deadly Revolution",
"Increase directional changes and damage for midair \u25a0 attacks with \u21a4\u21a6.",[new SkillTier(1,"Power: 18"+spacerLarge+"Direction changes: 2"+spacerLarge+"Dealt damage +30%",1,11,-1,[""]),new SkillTier(2,"Power: 20"+spacerLarge+"Direction changes: 2"+spacerLarge+"Dealt damage +35%",1,17,-1,[""]),new SkillTier(3,"Power: 22"+spacerLarge+"Direction changes: 2"+spacerLarge+"Dealt damage +45%",2,23,3,[""]),new SkillTier(4,"Power: 24"+spacerLarge+"Direction changes: 3"+spacerLarge+"Dealt damage +55%",
2,29,3,[""]),new SkillTier(5,"Power: 26"+spacerLarge+"Direction changes: 3"+spacerLarge+"Dealt damage +70%",3,36,6,[""]),new SkillTier(6,"Power: 28"+spacerLarge+"Direction changes: 3"+spacerLarge+"Dealt damage +85%",3,45,6,[""]),new SkillTier(7,"Power: 30"+spacerLarge+"Direction changes: 4"+spacerLarge+"Dealt damage +100%",5,54,9,[""])])]),new SkillCategory("ground","Ground",[new Skill("brutalDrive","Brutal Drive","Power Smash and its shockwaves are strengthened. Activate with \u25cf.",[new SkillTier(1,
"Power: 440"+spacerLarge+"Shockwave Power: 165",1,-1,-1,[""]),new SkillTier(2,"Power: 480"+spacerLarge+"Shockwave Power: 180"+spacerLarge+"Shockwave range: 105%",1,6,-1,[""]),new SkillTier(3,"Power: 520"+spacerLarge+"Shockwave Power: 195"+spacerLarge+"Shockwave range: 110%",1,12,3,[""]),new SkillTier(4,"Power: 560"+spacerLarge+"Shockwave Power: 210"+spacerLarge+"Shockwave range: 115%",2,18,3,[""]),new SkillTier(5,"Power: 600"+spacerLarge+"Shockwave Power: 225"+spacerLarge+"Shockwave range: 120%",
2,24,6,[""]),new SkillTier(6,"Power: 640"+spacerLarge+"Shockwave Power: 248"+spacerLarge+"Shockwave range: 125%",3,30,6,[""]),new SkillTier(7,"Power: 680"+spacerLarge+"Shockwave Power: 270"+spacerLarge+"Shockwave range: 130%",3,37,9,[""]),new SkillTier(8,"Power: 740"+spacerLarge+"Shockwave Power: 300"+spacerLarge+"Shockwave range: 135%",4,44,9,[""]),new SkillTier(9,"Power: 800"+spacerLarge+"Shockwave Power: 330"+spacerLarge+"Shockwave range: 140%",4,51,12,[""]),new SkillTier(10,"Power: 900"+spacerLarge+
"Shockwave Power: 400"+spacerLarge+"Shockwave range: 190%",6,60,12,[""])]),new Skill("parry","Parry","Hold \u25a0 on the ground to parry enemy attacks, add temporary invincibility, and trigger Berserk.",[new SkillTier(1,"Power: 100"+spacerLarge+"Duration of invincibility: 2.0s",1,4,-1,[""]),new SkillTier(2,"Power: 110"+spacerLarge+"Duration of invincibility: 2.3s",1,9,-1,[""]),new SkillTier(3,"Power: 120"+spacerLarge+"Duration of invincibility: 2.7s",1,14,3,[""]),new SkillTier(4,"Power: 130"+spacerLarge+
"Duration of invincibility: 3.0s",2,20,3,[""]),new SkillTier(5,"Power: 140"+spacerLarge+"Duration of invincibility: 3.3s",2,26,6,[""]),new SkillTier(6,"Power: 150"+spacerLarge+"Duration of invincibility: 3.7s",2,32,6,[""]),new SkillTier(7,"Power: 160"+spacerLarge+"Duration of invincibility: 4.0s",3,38,9,[""]),new SkillTier(8,"Power: 180"+spacerLarge+"Duration of invincibility: 4.3s",3,45,9,[""]),new SkillTier(9,"Power: 190"+spacerLarge+"Duration of invincibility: 4.7s",3,52,12,[""]),new SkillTier(10,
"Power: 250"+spacerLarge+"Duration of invincibility: 5.0s",4,59,12,[""])]),new Skill("punisher","Punisher","Deal multiple four-hit combos on the ground. Will increase damage and chance of Berserk.",[new SkillTier(1,"Power: 20",1,10,-1,[""]),new SkillTier(2,"Power: 40",2,21,-1,[""]),new SkillTier(3,"Power: 60",3,40,3,[""])]),new Skill("brandish","Brandish","A spinning attack with invincibility. Press \u21a4\u21a6 + \u25a0 after a four-hit combo on the ground.",[new SkillTier(1,"Power: 100"+spacerLarge+
"# of spins: 1",3,15,-1,[""]),new SkillTier(2,"Power: 110"+spacerLarge+"# of spins: 2",1,22,-1,[""]),new SkillTier(3,"Power: 120"+spacerLarge+"# of spins: 3",2,30,3,[""]),new SkillTier(4,"Power: 130"+spacerLarge+"# of spins: 4",3,39,3,[""]),new SkillTier(5,"Power: 150"+spacerLarge+"# of spins: 5",5,48,6,[""])])]),new SkillCategory("supplemental","Supplemental",[new Skill("berserk","Berserk","Attack an enemy multiple times consecutively for increased attack power and speed.",[new SkillTier(1,"Dealt damage +10% while Berserk",
1,-1,-1,[""]),new SkillTier(2,"Dealt damage +15% while Berserk",1,7,-1,[""]),new SkillTier(3,"Dealt damage +20% while Berserk",1,13,3,[""]),new SkillTier(4,"Dealt damage +25% while Berserk",2,19,3,[""]),new SkillTier(5,"Dealt damage +30% while Berserk",2,25,6,[""]),new SkillTier(6,"Dealt damage +35% while Berserk",3,31,6,[""]),new SkillTier(7,"Dealt damage +40% while Berserk",3,37,9,[""]),new SkillTier(8,"Dealt damage +45% while Berserk",4,43,9,[""]),new SkillTier(9,"Dealt damage +50% while Berserk",
4,49,12,[""]),new SkillTier(10,"Dealt damage +60% while Berserk",6,55,12,[""])]),new Skill("adrenaline","Adrenaline","Strength increases as HP decreases.",[new SkillTier(1,"Dealt damage +30% while HP decreased",1,-1,-1,[""]),new SkillTier(2,"Dealt damage +40% while HP decreased",1,6,-1,[""]),new SkillTier(3,"Dealt damage +50% while HP decreased",2,12,3,[""]),new SkillTier(4,"Dealt damage +60% while HP decreased",2,20,3,[""]),new SkillTier(5,"Dealt damage +70% while HP decreased",3,28,6,[""]),new SkillTier(6,
"Dealt damage +80% while HP decreased",3,38,6,[""]),new SkillTier(7,"Dealt damage +100% while HP decreased",4,51,9,[""])]),new Skill("paint","War Paint","Summon clones that unleash multiple attacks. (Use War Paint)",[new SkillTier(1,"Uses: 3"+spacerLarge+"Number of clones: 1"+spacerLarge+"Duration: 10s",2,5,-1,[""]),new SkillTier(2,"Uses: 3"+spacerLarge+"Number of clones: 1"+spacerLarge+"Duration: 15s",3,27,-1,[""]),new SkillTier(3,"Uses: 3"+spacerLarge+"Number of clones: 2"+spacerLarge+"Duration: 20s",
4,46,3,[""])]),new Skill("rage","Incite Rage","Exchange HP to trigger Berserk. (Use Incite Rage)",[new SkillTier(1,"Uses: 3"+spacerLarge+"Current HP decreased by 50%"+spacerLarge+"Duration +3s",1,9,-1,[""]),new SkillTier(2,"Uses: 4"+spacerLarge+"Current HP decreased by 60%"+spacerLarge+"Duration +6s",2,20,-1,[""]),new SkillTier(3,"Uses: 5"+spacerLarge+"Current HP decreased by 70%"+spacerLarge+"Duration +12s",3,34,3,[""])]),new Skill("will","Iron Will","Exhange HP to temporarily ignore knockback and take 1 damage from all attacks. (Use Iron Will)",
[new SkillTier(1,"Number of uses: 3"+spacerLarge+"Time effective: 8s",1,13,-1,[""]),new SkillTier(2,"Number of uses: 3"+spacerLarge+"Time effective: 12s",1,21,-1,[""]),new SkillTier(3,"Number of uses: 4"+spacerLarge+"Time effective: 12s",2,29,3,[""]),new SkillTier(4,"Number of uses: 4"+spacerLarge+"Time effective: 16s",3,40,3,[""]),new SkillTier(5,"Number of uses: 5"+spacerLarge+"Time effective: 20s",5,52,6,[""])])])]),skillsDwarf=new SkillType("dwarf","Dwarf Skills",[new SkillCategory("attack","Attack",
[new Skill("powerBomb","Power Bomb","Adds shockwaves to throwing attacks.",[new SkillTier(1,"Dealt damage +30% to throws.",1,-1,-1,[""]),new SkillTier(2,"Dealt damage +45%"+spacerLarge+"Shockwave range: 105%",1,6,-1,[""]),new SkillTier(3,"Dealt damage +60%"+spacerLarge+"Shockwave range: 110%",1,11,3,[""]),new SkillTier(4,"Dealt damage +75%"+spacerLarge+"Shockwave range: 115%",2,16,3,[""]),new SkillTier(5,"Dealt damage +90%"+spacerLarge+"Shockwave range: 120%",2,22,6,[""]),new SkillTier(6,"Dealt damage +110%"+
spacerLarge+"Shockwave range: 125%",3,28,6,[""]),new SkillTier(7,"Dealt damage +130%"+spacerLarge+"Shockwave range: 130%",3,34,9,[""]),new SkillTier(8,"Dealt damage +160%"+spacerLarge+"Shockwave range: 135%",4,40,9,[""]),new SkillTier(9,"Dealt damage +190%"+spacerLarge+"Shockwave range: 140%",4,47,12,[""]),new SkillTier(10,"Dealt damage +250%"+spacerLarge+"Shockwave range: 180%",5,55,12,[""])]),new Skill("fists","Lethal Fists","Increases the damage dealt for all bare-fisted attacks.",[new SkillTier(1,
"Dealt damage +20% to barehanded attacks",1,-1,-1,["Bare-handed attack range for normal four-hit combo increased (shown as small wind gusts emanating from punches)."]),new SkillTier(2,"Dealt damage +40% to barehanded attacks",1,7,-1,[""]),new SkillTier(3,"Dealt damage +60% to barehanded attacks",1,12,3,[""]),new SkillTier(4,"Dealt damage +80% to barehanded attacks",2,18,3,[""]),new SkillTier(5,"Dealt damage +100% to barehanded attacks",2,23,6,[""]),new SkillTier(6,"Dealt damage +120% to barehanded attacks",
3,29,6,[""]),new SkillTier(7,"Dealt damage +140% to barehanded attacks",3,35,9,[""]),new SkillTier(8,"Dealt damage +160% to barehanded attacks",4,41,9,[""]),new SkillTier(9,"Dealt damage +180% to barehanded attacks",4,48,12,[""]),new SkillTier(10,"Dealt damage +250% to barehanded attacks",5,56,12,[""])]),new Skill("eagleDive","Eagle Dive","A midair glide attack. (Double jump and \u2a2f).",[new SkillTier(1,"Allows glide attacks",1,3,-1,[""]),new SkillTier(2,"Drop bombs during glide attacks",1,10,-1,
[""]),new SkillTier(3,"Power of bombs: 70"+spacerLarge+"Bombs: 4",2,19,3,[""]),new SkillTier(4,"Power of bombs: 80"+spacerLarge+"Bombs: 5",3,30,3,[""]),new SkillTier(5,"Power of bombs: 90"+spacerLarge+"Bombs: 6",5,42,6,[""])]),new Skill("grandSmash","Grand Smash","A powerful attack which requires the temporary loss of your weapon. Activate with Power Smash. (\u25cf)",[new SkillTier(1,"Power: 110"+spacerLarge+"Power (Lightning): 36",1,9,-1,[""]),new SkillTier(2,"Power: 120"+spacerLarge+"Power (Lightning): 39",
1,17,-1,[""]),new SkillTier(3,"Power: 135"+spacerLarge+"Power (Lightning): 42",2,27,3,[""]),new SkillTier(4,"Power: 150"+spacerLarge+"Power (Lightning): 47",3,39,3,[""]),new SkillTier(5,"Power: 170"+spacerLarge+"Power (Lightning): 55",5,53,6,[""])]),new Skill("frenzy","Frenzy","A powerful rush attack. Activate by rapidly pressing \u25a0.",[new SkillTier(1,"Power: 40"+spacerLarge+"Duration: 1.5s",3,15,-1,[""]),new SkillTier(2,"Power: 45"+spacerLarge+"Duration: 2.0s",1,25,-1,[""]),new SkillTier(3,"Power: 50"+
spacerLarge+"Duration: 2.5s",2,36,3,[""]),new SkillTier(4,"Power: 60"+spacerLarge+"Duration: 3.0s",3,48,3,[""]),new SkillTier(5,"Power: 70"+spacerLarge+"Duration: 4.0s",5,60,6,[""])])]),new SkillCategory("tools","Tools",[new Skill("satchel","Bomb Satchel","Use a Bomb Satchel item to carry around and use bombs.",[new SkillTier(1,"Number of uses: 4",1,-1,-1,[""]),new SkillTier(2,"Number of uses: 6",1,8,-1,[""]),new SkillTier(3,"Number of uses: 8",2,20,3,[""]),new SkillTier(4,"Number of uses: 10",3,
33,3,[""]),new SkillTier(5,"Number of uses: 15",5,46,6,[""])]),new Skill("barrel","Fire Barrel","Use a Fire Barrel item to produce an exploding barrel that can be picked up and hurled.",[new SkillTier(1,"Number of uses: 3",1,9,-1,[""]),new SkillTier(2,"Number of uses: 4",1,13,-1,[""]),new SkillTier(3,"Number of uses: 5",2,24,3,[""]),new SkillTier(4,"Number of uses: 6",3,38,3,[""]),new SkillTier(5,"Number of uses: 9",5,52,6,[""])]),new Skill("infusion","Magma Infusion","Use a Lava Bracer item to add fire properties to any attack.",
[new SkillTier(1,"Number of uses: 3"+spacerLarge+"Duration: 15s",1,10,-1,[""]),new SkillTier(2,"Number of uses: 4"+spacerLarge+"Duration: 18s",1,17,-1,[""]),new SkillTier(3,"Number of uses: 5"+spacerLarge+"Duration: 21s",2,25,3,[""]),new SkillTier(4,"Number of uses: 6"+spacerLarge+"Duration: 25s",3,34,3,[""]),new SkillTier(5,"Number of uses: 12"+spacerLarge+"Duration: 35s",5,45,6,[""])]),new Skill("mastery","Powder Mastery","Increases damage of fire-enhanced physical attacks.",[new SkillTier(1,"Fire-enhanced physical attacks Dealt damage +20%",
1,14,-1,[""]),new SkillTier(2,"Fire-enhanced physical attacks Dealt damage +25%",1,19,-1,[""]),new SkillTier(3,"Fire-enhanced physical attacks Dealt damage +30%",1,24,3,[""]),new SkillTier(4,"Fire-enhanced physical attacks Dealt damage +35%",2,29,3,[""]),new SkillTier(5,"Fire-enhanced physical attacks Dealt damage +40%",2,34,6,[""]),new SkillTier(6,"Fire-enhanced physical attacks Dealt damage +50%",3,39,6,[""]),new SkillTier(7,"Fire-enhanced physical attacks Dealt damage +60%",3,44,9,[""]),new SkillTier(8,
"Fire-enhanced physical attacks Dealt damage +70%",4,49,9,[""]),new SkillTier(9,"Fire-enhanced physical attacks Dealt damage +80%",4,54,12,[""]),new SkillTier(10,"Fire-enhanced physical attacks Dealt damage +100%",5,59,12,[""])])]),new SkillCategory("supplemental","Supplemental",[new Skill("trinket","Trinket Maniac","Heal HP and equipment durability when picking up score items.",[new SkillTier(1,"HP Recovered +2"+spacerLarge+"Durability recovery +1",1,-1,-1,[""]),new SkillTier(2,"HP Recovered +3"+
spacerLarge+"Durability recovery +1",1,6,-1,[""]),new SkillTier(3,"HP Recovered +4"+spacerLarge+"Durability recovery +1",1,11,3,[""]),new SkillTier(4,"HP Recovered +5"+spacerLarge+"Durability recovery +2",2,16,3,[""]),new SkillTier(5,"HP Recovered +6"+spacerLarge+"Durability recovery +2",2,21,6,[""]),new SkillTier(6,"HP Recovered +7"+spacerLarge+"Durability recovery +2",2,26,6,[""]),new SkillTier(7,"HP Recovered +8"+spacerLarge+"Durability recovery +3",3,32,9,[""]),new SkillTier(8,"HP Recovered +9"+
spacerLarge+"Durability recovery +3",3,38,9,[""]),new SkillTier(9,"HP Recovered +10"+spacerLarge+"Durability recovery +3",4,45,12,[""]),new SkillTier(10,"HP Recovered +15"+spacerLarge+"Durability recovery +5",5,51,12,[""])]),new Skill("rockSkin","Rock Skin","Increased defense while pumped up. Activate by holding \u25a0.",[new SkillTier(1,"Damage taken -20% during Pump Up",1,5,-1,[""]),new SkillTier(2,"Damage taken -25% during Pump Up",1,13,-1,[""]),new SkillTier(3,"Damage taken -30% during Pump Up",
2,22,3,[""]),new SkillTier(4,"Damage taken -35% during Pump Up",3,33,3,[""]),new SkillTier(5,"Damage taken -50% during Pump Up",5,46,6,[""])]),new Skill("toughness","Toughness","Smaller attacks won't cause you to flinch.",[new SkillTier(1,"Damage resistance: 30",1,12,-1,[""]),new SkillTier(2,"Damage resistance: 45",1,20,-1,[""]),new SkillTier(3,"Damage resistance: 60",2,30,3,[""]),new SkillTier(4,"Damage resistance: 80",3,41,3,[""]),new SkillTier(5,"Damage resistance: 120",5,54,6,[""])])])]),skillsElf=
new SkillType("elf","Elf Skills",[new SkillCategory("bow","Bow and arrow",[new Skill("powerShot","Power Shot","Charge an arrow to unleash a powerful wind shot. Hold \u25cf and then release \u25cf to shoot.",[new SkillTier(1,"Power: 210",1,-1,-1,[""]),new SkillTier(2,"Power: 220"+spacerLarge+"Shockwave range 105%",1,5,-1,[""]),new SkillTier(3,"Power: 230"+spacerLarge+"Shockwave range 110%",1,11,3,[""]),new SkillTier(4,"Power: 240"+spacerLarge+"Shockwave range 115%",2,17,3,[""]),new SkillTier(5,"Power: 250"+
spacerLarge+"Shockwave range 120%",2,24,6,[""]),new SkillTier(6,"Power: 260"+spacerLarge+"Shockwave range 125%",3,31,6,[""]),new SkillTier(7,"Power: 270"+spacerLarge+"Shockwave range 130%",3,38,9,[""]),new SkillTier(8,"Power: 280"+spacerLarge+"Shockwave range 135%",4,45,9,[""]),new SkillTier(9,"Power: 290"+spacerLarge+"Shockwave range 140%",4,52,12,[""]),new SkillTier(10,"Power: 320"+spacerLarge+"Shockwave range 170%",6,60,12,[""])]),new Skill("rapid","Rapid Fire","Quickly loose a volley of arrows. Increase number of arrows with higher skill levels.",
[new SkillTier(1,"Shots in Volley +1",1,-1,-1,[""]),new SkillTier(2,"Shots in Volley +2",2,9,-1,[""]),new SkillTier(3,"Shots in Volley +3",3,18,3,[""]),new SkillTier(4,"Shots in Volley +4",5,30,3,[""])]),new Skill("quiver","Spacious Quiver","Increase the number of arrows you can carry.",[new SkillTier(1,"Arrow max +2",1,3,-1,[""]),new SkillTier(2,"Arrow max +4",1,12,-1,[""]),new SkillTier(3,"Arrow max +7",2,23,3,[""]),new SkillTier(4,"Arrow max +10",3,36,3,[""]),new SkillTier(5,"Arrow max +15",5,
50,6,[""])]),new Skill("impact","Impact Arrows","Fire an arrow that produces a shockwave. Higher skill levels boost range and power.",[new SkillTier(1,"Power: 50"+spacerLarge+"Shockwave range: 105%",1,8,-1,[""]),new SkillTier(2,"Power: 65"+spacerLarge+"Shockwave range: 110%",1,14,-1,[""]),new SkillTier(3,"Power: 80"+spacerLarge+"Shockwave range: 115%",2,20,3,[""]),new SkillTier(4,"Power: 95"+spacerLarge+"Shockwave range: 120%",2,27,3,[""]),new SkillTier(5,"Power: 110"+spacerLarge+"Shockwave range: 125%",
3,33,6,[""]),new SkillTier(6,"Power: 125"+spacerLarge+"Shockwave range: 130%",3,40,6,[""]),new SkillTier(7,"Power: 175"+spacerLarge+"Shockwave range: 150%",5,49,9,[""])]),new Skill("clone","Clone Strikes","Shoot more arrows when using crouched charge attacks and when shooting while dashing.",[new SkillTier(1,"Multiple shots +1",1,15,-1,[""]),new SkillTier(2,"Multiple shots +2",2,26,-1,[""]),new SkillTier(3,"Multiple shots +3",3,39,-1,[""]),new SkillTier(4,"Multiple shots +4",5,53,3,[""])])]),new SkillCategory("tools",
"Tools",[new Skill("toxic","Toxic Extract","Use the Toxic Extract to grant arrow and dagger attacks poison properties. (Use again to deactivate.)",[new SkillTier(1,"Number of uses: 20",1,-1,-1,[""]),new SkillTier(2,"Number of uses: 25",1,7,-1,[""]),new SkillTier(3,"Number of uses: 30",2,16,3,[""]),new SkillTier(4,"Number of uses: 35",3,25,3,[""]),new SkillTier(5,"Number of uses: 50",5,35,6,[""])]),new Skill("dagger","Holdout Dagger","Use Holdout Dagger to produce a dagger to attack with.",[new SkillTier(1,
"Number of uses: 3",1,4,-1,[""]),new SkillTier(2,"Number of uses: 4",1,10,-1,[""]),new SkillTier(3,"Number of uses: 5",2,19,3,[""]),new SkillTier(4,"Number of uses: 6",2,30,3,[""]),new SkillTier(5,"Number of uses: 9",3,46,6,[""])]),new Skill("oil","Salamander Oil","Use the Salamander Oil to grant arrow and dagger attacks fire properties. (Use again to deactivate.)",[new SkillTier(1,"Number of uses: 20",1,13,-1,[""]),new SkillTier(2,"Number of uses: 25",1,22,-1,[""]),new SkillTier(3,"Number of uses: 30",
2,33,3,[""]),new SkillTier(4,"Number of uses: 35",3,44,3,[""]),new SkillTier(5,"Number of uses: 50",5,57,6,[""])])]),new SkillCategory("supplemental","Supplemental",[new Skill("lore","Elemental Lore","Use spirit magic to attack. Activate by holding \u25a0.",[new SkillTier(1,"Enables Spirit magic use",1,-1,-1,[""]),new SkillTier(2,"Spirit magic elemental Dealt damage +20%",1,6,-1,[""]),new SkillTier(3,"Spirit magic elemental Dealt damage +30%",1,11,3,[""]),new SkillTier(4,"Spirit magic elemental Dealt damage +40%",
2,16,3,[""]),new SkillTier(5,"Spirit magic elemental Dealt damage +50%",2,21,6,[""]),new SkillTier(6,"Spirit magic elemental Dealt damage +60%",2,26,6,[""]),new SkillTier(7,"Spirit magic elemental Dealt damage +70%",3,32,9,[""]),new SkillTier(8,"Spirit magic elemental Dealt damage +80%",3,37,9,[""]),new SkillTier(9,"Spirit magic elemental Dealt damage +90%",4,43,12,[""]),new SkillTier(10,"Spirit magic elemental Dealt damage +100%",5,50,12,[""])]),new Skill("boots","Deadly Boots","Add your boots' DEF to kick attack power. Higher Skill levels increase this boost.",
[new SkillTier(1,"Kick attack + 50% of boot defense",1,-1,-1,[""]),new SkillTier(2,"Kick attack + 75% of boot defense",1,7,-1,[""]),new SkillTier(3,"Kick attack + 100% of boot defense",1,12,3,[""]),new SkillTier(4,"Kick attack + 125% of boot defense",2,17,3,[""]),new SkillTier(5,"Kick attack + 150% of boot defense",2,23,6,[""]),new SkillTier(6,"Kick attack + 175% of boot defense",3,29,6,[""]),new SkillTier(7,"Kick attack + 200% of boot defense",3,35,9,[""]),new SkillTier(8,"Kick attack + 230% of boot defense",
4,41,9,[""]),new SkillTier(9,"Kick attack + 260% of boot defense",4,47,12,[""]),new SkillTier(10,"Kick attack + 300% of boot defense",6,54,12,[""])]),new Skill("backstab","Backstab","Increase damage when attakcing an enemy from behind with a dagger.",[new SkillTier(1,"Dagger back attack Dealt damage +80%",1,5,-1,[""]),new SkillTier(2,"Dagger back attack Dealt damage +100%",1,10,-1,[""]),new SkillTier(3,"Dagger back attack Dealt damage +120%",1,15,3,[""]),new SkillTier(4,"Dagger back attack Dealt damage +135%",
2,20,3,[""]),new SkillTier(5,"Dagger back attack Dealt damage +155%",2,25,6,[""]),new SkillTier(6,"Dagger back attack Dealt damage +175%",3,30,6,[""]),new SkillTier(7,"Dagger back attack Dealt damage +195%",3,36,9,[""]),new SkillTier(8,"Dagger back attack Dealt damage +210%",4,42,9,[""]),new SkillTier(9,"Dagger back attack Dealt damage +230%",4,48,12,[""]),new SkillTier(10,"Dagger back attack Dealt damage +300%",5,55,12,[""])]),new Skill("hardened","Battle Hardened","Reduce knockback chance and damage taken while charging arrows.",
[new SkillTier(1,"Damage taken -20% while aiming"+spacerLarge+"Knockback resistance: 50",1,9,-1,[""]),new SkillTier(2,"Damage taken -25% while aiming"+spacerLarge+"Knockback resistance: 66",1,18,-1,[""]),new SkillTier(3,"Damage taken -30% while aiming"+spacerLarge+"Knockback resistance: 75",2,28,3,[""]),new SkillTier(4,"Damage taken -35% while aiming"+spacerLarge+"Knockback resistance: 80",3,39,3,[""]),new SkillTier(5,"Damage taken -50% while aiming"+spacerLarge+"Knockback resistance: 83",5,51,6,
[""])])])]),skillsSorceress=new SkillType("sorceress","Sorceress Skills",[new SkillCategory("","",[new Skill("","","\u21a5 + \u21a7 + \u25a0 .",[new SkillTier(1,"",1,-1,-1,[""]),new SkillTier(1,"",1,-1,-1,[""]),new SkillTier(1,"",1,-1,-1,[""])])]),new SkillCategory("","",[new Skill("","","\u21a5 + \u21a7 + \u25a0 .",[new SkillTier(1,"",1,-1,-1,[""]),new SkillTier(1,"",1,-1,-1,[""]),new SkillTier(1,"",1,-1,-1,[""])])]),new SkillCategory("","",[new Skill("","","\u21a5 + \u21a7 + \u25a0 .",[new SkillTier(1,
"",1,-1,-1,[""]),new SkillTier(1,"",1,-1,-1,[""]),new SkillTier(1,"",1,-1,-1,[""])])])]),skillsWizard=new SkillType("wizard","Wizard Skills",[new SkillCategory("","",[new Skill("","","\u21a5 + \u21a7 + \u25a0 .",[new SkillTier(1,"",1,-1,-1,[""]),new SkillTier(1,"",1,-1,-1,[""]),new SkillTier(1,"",1,-1,-1,[""])])]),new SkillCategory("","",[new Skill("","","\u21a5 + \u21a7 + \u25a0 .",[new SkillTier(1,"",1,-1,-1,[""]),new SkillTier(1,"",1,-1,-1,[""]),new SkillTier(1,"",1,-1,-1,[""])])]),new SkillCategory("",
"",[new Skill("","","\u21a5 + \u21a7 + \u25a0 .",[new SkillTier(1,"",1,-1,-1,[""]),new SkillTier(1,"",1,-1,-1,[""]),new SkillTier(1,"",1,-1,-1,[""])])])]),skillsList=[skillsCommon,skillsFighter,skillsAmazon,skillsDwarf,skillsElf,skillsSorceress,skillsWizard];function getSkillType(b){let a={};skillsList.forEach(c=>{c.name===b&&(a=c)});return a}
function getSkillTier(b,a,c,e){let d={};skillsList.forEach(f=>{f.name===b&&f.categoryGroup.forEach(k=>{k.name===a&&k.skillGroup.forEach(h=>{h.name===c&&h.tierGroup.forEach(n=>{n.level===e&&(d=n)})})})});return d};const characterClassNames="Fighter Amazon Dwarf Elf Sorceress Wizard".split(" "),maxSkillPoints=155,resetModalInfoText='Do you wish to include "Deep Pockets" when resetting?',skillIdSuffx="-name-desc",skillEffectIdSuffx="-effects",skillConditionsIdSuffx="-conditions",skillElemIdSuffixCost="-cost",skillElemIdSuffixPlayer="-player",skillElemIdSuffixCategory="-category",skillEffectsCurrentIdSuffix="-current",skillEffectsNextIdSuffix="-next",tableCommonBodyId="common-skills-table-body",skillRowDataId=
"data-row-id",skillDataCellId="data-cell-id",skillDataElementId="data-elem-id",skillDataIdType="data-skill-type",skillDataIdCategory="data-skill-category",skillDataIdCategoryLabel="data-skill-category-label",skillDataIdSkill="data-skill-name",inputNonInteractive="table-input-non-interactable",inputSkillLevel="input-skill-level";let playerSelectionPrevious="",currentSkillPoints=maxSkillPoints,commonSkillTiers=[];
function processSkillTierPropertiesForOutput(b,a,c=null){switch(b){case "effect":return"Next: "+a;case "cost":return 0<a?"Skill point cost: "+a+" point(s)":"";case "player":return 0<a?"Player LV must be at least LV "+a+".":"";case "category":return 0<a&&c?"The "+c+" category skill must be LV "+a+".":"";default:return""}}
function enableResetButtons(){let b=document.getElementsByClassName("reset-button");for(let a=0;a<b.length;a++)b[a].setAttribute("disabled","false"),b[a].removeAttribute("disabled")}function updateTotalCurrentSkillPoints(b,a,c){let e=document.getElementById("current-total-points");0<c?e.setAttribute("value",Number(e.getAttribute("value"))-b):e.setAttribute("value",Number(e.getAttribute("value"))+a)}
function resetTotalCurrentSkillPoints(b=0){document.getElementById("current-total-points").setAttribute("value",maxSkillPoints-b)}function populateSkillEffects(b,a,c,e){b.innerText=c;a.innerText=e}function populateSkillConditions(b,a,c){let e=["cost","player","category"];for(let d=0;d<b.length;d++)b[d].innerText="category"===e[d]?processSkillTierPropertiesForOutput(e[d],a[d],c):processSkillTierPropertiesForOutput(e[d],a[d])}
function updateCategoryLevel(b,a){a=Number(b.getAttribute("value"))+a;b.setAttribute("value",a)}function rollbackInputValue(b,a){b.value=a;b.setAttribute("value",a)}function limitTrigger(b){b.forEach(a=>{a.classList.contains("limiter-triggered")||a.classList.add("limiter-triggered")})}function limitTriggerReset(b){b.forEach(a=>{a.classList.contains("limiter-triggered")&&a.classList.remove("limiter-triggered")})}
function getFewerChildrenFromParentChildren(b,a,c,e,d){let f=Array(3),k=[];for(const h of b.children)h.getAttribute(a)===c?f[0]=h:h.getAttribute(a)===e?f[1]=h:h.getAttribute(a)===d&&(f[2]=h);f.forEach(h=>{k.push(h)});return k}
function updateSkillLevel(b){var a=document.getElementById("current-total-points"),c=b.getAttribute(skillDataIdSkill),e=b.getAttribute(skillDataIdType),d=b.getAttribute(skillDataIdCategory);let f=Number(b.getAttribute("max")),k=document.getElementById(c),h=document.getElementById(d).getElementsByTagName("input")[0],n=Number(a.getAttribute("value")),r=Number(b.getAttribute("value")),l=Number(b.value),q=l+1,t=l-r,g={},m={};a=[a.parentElement,h.parentElement];0<l?g=getSkillTier(e,d,c,l):g.effect="";
q>f?(m.cost="",m.minLevelPlayer="",m.minLevelCategory="",m.effect="--"):m=getSkillTier(e,d,c,q);0<t&&n>=Number(g.cost)||0>t?0<t&&Number(h.getAttribute("value"))>=Number(g.minLevelCategory)||0>t?(d=getFewerChildrenFromParentChildren(k,skillDataCellId,c+skillEffectIdSuffx,c+skillConditionsIdSuffx),e=getFewerChildrenFromParentChildren(d[0],skillDataElementId,c+skillEffectsCurrentIdSuffix,c+skillEffectsNextIdSuffix),c=getFewerChildrenFromParentChildren(d[1],skillDataElementId,c+skillElemIdSuffixCost,
c+skillElemIdSuffixPlayer,c+skillElemIdSuffixCategory),d=[m.cost,m.minLevelPlayer,m.minLevelCategory],b.setAttribute("value",l),populateSkillConditions(c,d,b.getAttribute(skillDataIdCategoryLabel)),populateSkillEffects(e[0],e[1],g.effect,m.effect),updateCategoryLevel(h,t),updateTotalCurrentSkillPoints(Number(g.cost),Number(m.cost),t),limitTriggerReset(a)):(limitTrigger([a[1]]),b.value=r):(limitTrigger([a[0]]),b.value=r)}
function elementBuilderInnerElements(b,a){a.forEach(c=>{b.appendChild(c)});return b}
function resetTableBody(b,a=[]){let c=document.getElementById("current-total-points");for(let r in b){var e=document.getElementById(b[r]),d=e.children;e=e.getElementsByClassName(inputNonInteractive);for(let l=0;l<d.length;l++){let q=d[l].getElementsByClassName(inputSkillLevel)[0];var f=d[l].getAttribute("id"),k=q.getAttribute(skillDataIdType),h=q.getAttribute(skillDataIdCategory),n=q.getAttribute(skillDataIdSkill);k=getSkillTier(k,h,n,1);n=getFewerChildrenFromParentChildren(d[l],skillDataCellId,f+
skillEffectIdSuffx,f+skillConditionsIdSuffx);h=getFewerChildrenFromParentChildren(n[0],skillDataElementId,f+skillEffectsCurrentIdSuffix,f+skillEffectsNextIdSuffix);f=getFewerChildrenFromParentChildren(n[1],skillDataElementId,f+skillElemIdSuffixCost,f+skillElemIdSuffixPlayer,f+skillElemIdSuffixCategory);n=[k.cost,k.minLevelPlayer,k.minLevelCategory];q.setAttribute("value",0);q.value=0;populateSkillConditions(f,n,q.getAttribute(skillDataIdCategoryLabel));populateSkillEffects(h[0],h[1],"",k.effect)}for(d=
0;d<e.length;d++)e[d].setAttribute("value",0),limitTriggerReset([e[d].parentElement])}0<a.length||resetTotalCurrentSkillPoints();limitTriggerReset([c.parentElement])}
function populateSkillTable(b,a,c){let e=document.getElementById(a),d=document.createElement("tbody");document.getElementById(c).innerText=b.label;b.categoryGroup.forEach(f=>{let k=0,h=document.createElement("td"),n=document.createElement("p");document.createElement("form");let r=document.createElement("label"),l=document.createElement("input"),q=document.createTextNode(f.label+" Skill"),t=document.createTextNode("Current LV: ");f.skillGroup.forEach(g=>{document.createTextNode(g.label.toString());
document.createTextNode(g.description.toString());let m=document.createElement("tr"),w=document.createElement("td"),u=document.createElement("td"),x=document.createElement("td"),v=document.createElement("td"),y=document.createElement("p"),z=document.createElement("p"),A=document.createElement("p"),B=document.createElement("p"),C=document.createElement("p"),D=document.createElement("p"),E=document.createElement("p"),F=document.createElement("p"),G=document.createTextNode(g.label),H=document.createTextNode(g.description),
I=document.createTextNode(""),J=document.createTextNode("Next"),K=document.createTextNode(g.tierGroup[0].effect),L=document.createTextNode(processSkillTierPropertiesForOutput("cost",g.tierGroup[0].cost)),M=document.createTextNode(processSkillTierPropertiesForOutput("player",g.tierGroup[0].minLevelPlayer)),N=document.createTextNode(processSkillTierPropertiesForOutput("category",g.tierGroup[0].minLevelCategory,f.label)),p=document.createElement("input");v.setAttribute(skillDataCellId,g.name+skillConditionsIdSuffx);
B.setAttribute(skillDataElementId,g.name+skillElemIdSuffixCost);C.setAttribute(skillDataElementId,g.name+skillElemIdSuffixPlayer);D.setAttribute(skillDataElementId,g.name+skillElemIdSuffixCategory);v.classList.add("skills-table-wide-cell");B.appendChild(L);C.appendChild(M);D.appendChild(N);elementBuilderInnerElements(v,[B,C,D]);p.setAttribute("type","number");p.setAttribute("step","1");p.setAttribute("onKeyDown","return false");p.setAttribute("min","0");p.setAttribute("value","0");p.setAttribute("max",
g.tierGroup.length.toString());p.setAttribute(skillDataIdType,b.name);p.setAttribute(skillDataIdCategory,f.name);p.setAttribute(skillDataIdCategoryLabel,f.label);p.setAttribute(skillDataIdSkill,g.name);p.classList.add(inputSkillLevel);x.appendChild(p);x.addEventListener("input",function(O){updateSkillLevel(O.target)});u.setAttribute(skillDataCellId,g.name+skillEffectIdSuffx);z.setAttribute("class","skills-text-element-next-header");y.setAttribute(skillDataElementId,g.name+skillEffectsCurrentIdSuffix);
A.setAttribute(skillDataElementId,g.name+skillEffectsNextIdSuffix);u.classList.add("skills-table-widest-cell");z.appendChild(J);A.appendChild(K);y.appendChild(I);elementBuilderInnerElements(u,[y,z,A]);w.setAttribute(skillDataCellId,g.name+skillIdSuffx);E.appendChild(G);F.appendChild(H);elementBuilderInnerElements(w,[E,F]);m.setAttribute("id",g.name);1>k&&(h.setAttribute("id",f.name),l.setAttribute("type","number"),l.setAttribute("value","0"),l.setAttribute("min","0"),l.setAttribute("readonly",""),
l.classList.add(inputNonInteractive),r.appendChild(t),r.appendChild(l),n.appendChild(q),elementBuilderInnerElements(h,[n,r]),m.appendChild(h));elementBuilderInnerElements(m,[w,u,x,v]);k++;d.appendChild(m)});h.setAttribute("rowspan",k)});d.setAttribute("id",a);e.parentNode.replaceChild(d,e)}
function updateSkillsData(){const b=document.getElementById("tables-container");let a=document.getElementById("characters-list").value;if(a!==playerSelectionPrevious){let c=document.getElementById("common-skills-table"),e=document.getElementById("class-skills-table"),d=getSkillType(a);if(c.getAttribute("data-table-populated"))resetTableBody(["common-skills-table-body"]);else{let f=getSkillType("common");populateSkillTable(f,tableCommonBodyId,"common-skills-table-label");c.setAttribute("data-table-populated",
"")}playerSelectionPrevious=a;populateSkillTable(d,"class-skills-table-body","class-skills-table-label");e.setAttribute("data-table-populated","");"block"!==b.style.display&&(b.style.display="block");resetTotalCurrentSkillPoints();enableResetButtons()}};function prepCollapse(){let b=document.getElementsByClassName("collapsible");for(let a=0;a<b.length;a++)b[a].addEventListener("click",function(){this.classList.toggle("active");var c=this.nextElementSibling;c.style.maxHeight=c.style.maxHeight?null:c.scrollHeight+"px"})}"loading"===document.readyState?document.addEventListener("DOMContentLoaded",prepCollapse):prepCollapse();
